package com.nagarro.ticketmanagement.service;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.nagarro.ticketmanagement.dao.TicketRepository;
import com.nagarro.ticketmanagement.model.Employee;
import com.nagarro.ticketmanagement.model.Ticket;

/**
 * handle all the business logic related Ticket
 * 
 * @author nishantgarg
 *
 */
@Service
public class TicketService {

	@Autowired
	private TicketRepository ticketRepository;

	/**
	 * create the ticket while saving through database
	 * 
	 * @param ticket
	 */
	public void createTicket(Ticket ticket) {
		ticketRepository.save(ticket);
	}

	/**
	 * find all employee's ticket generated by given employee
	 * 
	 * @param employee
	 * @return {@link List <{@link Ticket}>
	 */
	public List<Ticket> getAllTickets(Employee employee) {
		return ticketRepository.findAllTicketByEmployee(employee);
	}

	/**
	 * find all the tickets
	 * 
	 * @return {@link List <{@link Ticket}>
	 */
	public List<Ticket> getAllTickets() {
		return (List<Ticket>) ticketRepository.findAll();
	}

	/**
	 * find the ticket by its id and if the ticket is not present then it will
	 * return the null list
	 * 
	 * @param id
	 * @return @return {@link Optional <{@link Ticket}>
	 */
	public Optional<Ticket> getTicketById(int id) {
		return ticketRepository.findById(id);
	}

	/**
	 * It will assign the ticket to a certain admin
	 * 
	 * @param ticket
	 */
	public void assigTicket(Ticket ticket) {
		ticketRepository.save(ticket);
	}

	/**
	 * it will update the status of the given ticket set by certain admin
	 * 
	 * @param ticket
	 */
	public void updateStatus(Ticket ticket) {
		ticketRepository.save(ticket);
	}
}
