package com.nagarro.ticketmanagement.dao;

import java.util.List;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import com.nagarro.ticketmanagement.model.Employee;
import com.nagarro.ticketmanagement.model.Ticket;

/**
 * comment repository handle all operation related to Ticket database
 * 
 * @author nishantgarg
 *
 */
@Repository
public interface TicketRepository extends CrudRepository<Ticket, Integer> {

	/**
	 * It will return list of all tickets generated by given employee
	 * 
	 * @param employee
	 * @return {@link List <{@link Ticket }>
	 */
	public List<Ticket> findAllTicketByEmployee(Employee employee);

}
